### ISSUE TITLE
Two-argument versions of math::log are dangerous to use and don't appear to be used anywhere

### ISSUE THREAD

**Issue by timsong-yale** [rabauke/trng4#10]
For example,

    inline float log(float b, float x) {
      static float last_b(2.0f);
      static float last_log_b(1.0f/log(last_b));
      if (b!=last_b) {
        last_b=b;
        last_log_b=1.0f/log(b);
      }
      return log(x)*last_log_b;
    }

Using function-local statics to cache the last base makes it unsafe to call these functions concurrently. While it is possible to add the necessary synchronization, since those functions do not appear to be used anywhere in TRNG it might be easier to just remove them.

**Comment by rabauke** [comment]
Your are right, I completely agree. This will be fixed in the next release. Many thanks for your feedback.
