### ISSUE TITLE
xoroshiro type generators

### ISSUE THREAD

**Issue by jeffpollock9** [rabauke/trng4#13]
Firstly many thanks for your library!

I was wondering if there were any plans to add the generators from [here](http://xoroshiro.di.unimi.it/). In particular the [xoroshiro128plus](http://xoroshiro.di.unimi.it/xoroshiro128plus.c). They appear to be quite fast and have good properties so it would be nice to have them in your library under the C++11 RNG concept (the website provides a basic C implementation which is not too hard to tweak).

I would be more than happy to contribute to this where I could.

**Comment by rabauke** [comment]
If time permits I may implement this generator. I see, however, no easy way to implement splitting methods for this kind generator.
