### ISSUE TITLE
Cannot run make install directly

### ISSUE THREAD

**Issue by torquil** [rabauke/trng4#14]
With most software, it is possible to run "make install" without running "make" before, and everything will be taken care of automatically by the dependencies in the makefile. However, with TRNG, I get the following if I run make install directly:

make[1]: Entering directory '/tmp/trng-4.20/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I..   -g -O2 -MT minstd.lo -MD -MP -MF .deps/minstd.Tpo -c -o minstd.lo minstd.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -g -O2 -MT minstd.lo -MD -MP -MF .deps/minstd.Tpo -c minstd.cc  -fPIC -DPIC -o .libs/minstd.o
minstd.cc:33:10: fatal error: trng/minstd.hpp: No such file or directory
 #include <trng/minstd.hpp>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:495: minstd.lo] Error 1
make[1]: Leaving directory '/tmp/trng-4.20/src'
make: *** [Makefile:388: install-recursive] Error 1

If I run "make" and then "make install", it works. Is something wrong with the dependencies in the makefile?

**Comment by rabauke** [comment]
This has been fixed in version 4.21.
