### ISSUE TITLE
Weibull constructor documentation mistake

### ISSUE THREAD

**Issue by vchz** [rabauke/trng4#17]
Hello,
Thanks a lot for your library, it has been very useful to me so far and I really don't know how I would proceed without it. I use version 4.22.
I've noticed an inconsistency between the constructor in weibull_dist.hpp and the documentation. Nothing big, but though a bit sill, maybe you are aware of it already.

In the 4.22 the constructor is declared as :
`weibull_dist(result_type theta, result_type beta)`
While in the documentation it is said to be :
`weibull_dist(result_type beta, result_type theta)`

There is as far as I tested, no problem with this weibull distribution as long as you use the good declaration (the one of the hpp file).

Thanks !
Victor

**Comment by rabauke** [comment]
Thanks for drawing my attention to this documentation issue. Has been fixed in the development branch.
