### ISSUE TITLE
Question about TRNG and RNGTS

### ISSUE THREAD

**Issue by EliasCombarro** [rabauke/trng4#18]
Dear Prof. Bauke,

My name is Elías F. Combarro and I am an associate professor at the Computer Science Department of the University of Oviedo (Spain). 

I have just found your TRNG library, which I think interesting. I have read in the documentation that you used the Ising model tests from RNGTS. I am very interested in using those tests, but I the code seems to be no longer available at the RNGTS webpage. Would you know where I can find it or if there is any other implementation of those tests? 

Thank you very much in advance

Best,

Elías F. Combarro
Associate Professor
Computer Science Department 
University of Oviedo - Spain

**Comment by rabauke** [comment]
When you want to know what happened to the RNGTS, you should probably ask the authors of this library, see https://arxiv.org/abs/math/0410385 If you are particularly interested in the Monte Carlo calculation of the energy of the Ising model you can find an implementation of the Wolff cluster update algorithm in `examples/Ising.cc`.

**Comment by EliasCombarro** [comment]
Thank you for your answer and sorry if my question was inappropriate
