### ISSUE TITLE
BUILD_SHARED_LIBS

### ISSUE THREAD

**Issue by joseasoler** [rabauke/trng4#24]
To generate static/shared builds of a library in CMake, it is possible to define a single target (trng4 instead of trng4_shared and trng4_static), and let the user define the [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) CMake variable to specify if they want to build a static or shared library. Another advantage is that CMake projects using trng4 with find_package or FetchContent would be able to link against the trng4 target and their code would build properly regardless of if the found library is static or dynamic. Currently they need to decide beforehand if they want to link against the trng4_static or the trng4_shared library.

If you think this feature is a good idea I can implement it and prepare a pull request. I have noticed that there is a special case for trng4_shared on Windows so I would also make sure that building keeps working on that platform as well.

**Comment by rabauke** [comment]
Sounds reasonable. I may consider this as a future enhancement if time permits. PRs are welcome.
