### ISSUE TITLE
Save the internal state and restart

### ISSUE THREAD

**Issue by dessteph** [rabauke/trng4#28]
Hi,
It is mentioned in the documentation but I can't find any way to save the internal state of a random number generator to resume in that same state on another execution.
Is there an accurate example to achieve that?
Could you guide me to some documentation that explain how to do?

**Comment by rabauke** [comment]
Dear @dessteph, there are two ways to save the internal state of an engine:

1. Copy an instance to another one.
2. Write an engine into an i/o stream and read this output later again.

The following code snipped illustrates approach 1.

```cpp
#include <cstdlib>
#include <iostream>
// include TRNG header files
#include <trng/yarn2.hpp>
#include <trng/normal_dist.hpp>

int main() {
  // random number engine
  trng::yarn2 R;
  // normal distribution with mean 6 and standard deviation 2
  trng::normal_dist<> normal(6.0, 2.0);
  trng::yarn2 R_backup;
  // save the internal state of R into R_backup
  R_backup = R;
  // generate 10 normal distributed random numbers
  for (int i{0}; i < 10; ++i)
    std::cout << normal(R) << '\n';
  // restore internal state from R_backup
  R = R_backup;
  // generate the sam 10 normal distributed random numbers again
  for (int i{0}; i < 10; ++i)
    std::cout << normal(R) << '\n';
  return EXIT_SUCCESS;
}
```
